spring:
  application:
    name: cloudapp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.120.51.209:3306/estore
    username: root
    password: root
  redis:
    host: 47.120.51.209
    port: 6379
server:
  port: 8080
